# -*- coding: cp1252 -*-
#Side note: I got the questions from a PDF and the coding of the text defaulted to this. 

quizdict={"""1. An economy that is fully employing all its \
productive resources but allocating less to \
investment than to consumption will most likely \
be at which of the following positions on the \
production possibilities curve?
\n (A) A (TOP)
\n (B) B (MIDDLE)
\n (C) C (BOTTOM)
\n (D) D (INSIDE)
\n(E) E  (OUTSIDE)""":"C",\

"""2. Assume that land can be used either for
producing grain or for grazing cattle to produce
beef. The opportunity cost of converting an acre
from cattle grazing to grain production is the
\n(A) market value of the extra grain that is
produced
\n(B) total amount of beef produced
\n(C) number of extra bushels of grain that are
produced
\n(D) amount by which beef production decreases
\n(E) profits generated by the extra production
of grain""":"D",\

"""3. Which of the following will occur as a result of
an improvement in technology?
\n(A) The aggregate demand curve will shift to
the right.
\n(B) The aggregate demand curve will shift to
the left.
\n(C) The aggregate supply curve will shift to
the right.
\n(D) The aggregate supply curve will shift to
the left.
\n(E) The production possibilities curve will
shift inward.""":"C",\

"""4. Increases in real income per capita are made
possible by
\n(A) improved productivity
\n(B) a high labor/capital ratio
\n(C) large trade surpluses
\n(D) stable interest rates
\n(E) high protective tariffs""":"A",\

"""5. Which of the following is an example of
“investment" as used in economics?
\n(A) A schoolteacher purchases 10,000 shares
of stock in an automobile company.
\n(B) Newlyweds purchase a previously
owned home.
\n(C) One large automobile firm purchases
another large automobile firm.
\n(D) A farmer purchases $10,000 worth of
government securities.
\n(E) An apparel company purchases 15 new
sewing machines.""":"E",\

"""6. The United States Department of Labor defines
an individual as unemployed if the person
\n(A) does not hold a paying job
\n(B) has been recently fired
\n(C) works part time but needs full-time work
\n(D) is without a job but is looking for work
\n(E) wants a job but is not searching because he
or she thinks none is available""":"D",\

"""7. Assume that a country with an open economy
has a fixed exchange-rate system and that its
currency is currently overvalued in the foreign
exchange market. Which of the following must
be true at the official exchange rate?
\n(A) The quantity of the country’s currency
supplied is less than the quantity demanded.
\n(B) The quantity of the country’s currency
supplied exceeds the quantity demanded.
\n(C) The demand curve for the country’s currency
is horizontal.
\n(D) The supply curve for the country’s currency
is horizontal.
\n(E) The domestic interest rate is equal to the
interest rate in the rest of the world.""":"B",\

"""8. Which of the following workers is most likely to
be classified as structurally unemployed?
\n(A) A high school teacher who is unemployed
during the summer months
\n(B) A recent college graduate who is looking for
her first job
\n(C) A teenager who is seeking part-time
employment at a fast-food restaurant
\n(D) A worker who is unemployed because his
skills are obsolete
\n(E) A person who reenters the job market after
relocating""":"D",\

"""9. According to the classical model, an increase in
the money supply causes an increase in which
of the following in the long run?\n
I. Real gross domestic product\n
II. Nominal gross domestic product\n
III. Nominal wages
\n(A) I only
\n(B) II only
\n(C) III only
\n(D) II and III only
\n(E) I, II, and III""":"D",\

"""10. The diagram above shows aggregate supply
curves AS1, AS2, and AS3. Which of the
following statements is true?
\n(A) AS2 reflects wage and price rigidity.
\n(B) AS1 reflects greater wage and price
flexibility than AS2.
\n(C) AS2 reflects greater wage and price
flexibility than AS1 and AS3.
\n(D) The shift from AS1 to AS3 is due to a
decrease in nominal wages.
\n(E) The shift from AS3 to AS1 is due to an
increase in oil prices.""":"C",\

"""11. An increase in which of the following would
cause the long-run aggregate supply curve to
shift to the right?
\n(A) Corporate income tax rates
\n(B) Aggregate demand
\n(C) Labor productivity
\n(D) The average wage rate
\n(E) The price level""":"C",\

"""12. As income level increases from $500 to $1,000,
consumption increases from $700 to $1,100.
The marginal propensity to consume is equal to
\n(A) 1.10
\n(B) 0.80
\n(C) 0.70
\n(D) 0.50
\n(E) 0.10""":"B",\

"""13. In the circular flow diagram of an economy,
which of the following is true?
\n(A) Businesses pay wages, rent, interest, and
profits to households in return for use of
factors of production.
\n(B) Businesses purchase goods and services from
households in return for money payments.
\n(C) Households pay wages, rent, interest, and
profits to businesses in return for use of
factors of production.
\n(D) The relationship between households and
businesses exists only in a traditional
society.
\n(E) The relationship between households and
businesses exists only in a command
economy.""":"A",\

"""14. Which of the following would most likely lead
to a decrease in aggregate demand?
\n(A) A decrease in taxes
\n(B) A decrease in interest rates
\n(C) An increase in household savings
\n(D) An increase in household consumption
\n(E) An increase in business firms’ purchases of
capital equipment from retained earnings""":"C",\

"""15. According to the Keynesian model, equilibrium
output of an economy may be less than the
full-employment level of output because at
full employment
\n(A) sufficient income may not be generated to
keep workers above the subsistence level
\n(B) there might not be enough demand by firms
and consumers to buy that output
\n(C) workers may not be willing to work the
hours necessary to produce the output
\n(D) interest rates might not be high enough
to provide the incentive to finance the
production
\n(E) banks may not be willing to lend enough
money to support the output""":"B",\

"""16. If the Federal Reserve lowers reserve
requirements, which of the following is most
likely to happen to interest rates and nominal
gross domestic product?
\n(A) Increase Decrease
\n(B) Increase Increase
\n(C) Decrease Decrease
\n(D) Decrease Increase
\n(E) No change No change""":"D",\

"""17. If the marginal propensity to consume is
0.9, what is the maximum amount that the
equilibrium gross domestic product could
change if government expenditures increase
by $1 billion?
\n(A) It could decrease by $9 billion.
\n(B) It could increase by $0.9 billion.
\n(C) It could increase by $1 billion.
\n(D) It could increase by $9 billion.
\n(E) It could increase by $10 billion.""":"E",\

"""18. Expansionary fiscal policy will be most effective
in increasing real gross domestic product when
\n(A) the aggregate supply curve is horizontal
\n(B) the economy is at or above full employment
output
\n(C) transfer payments are decreased, while
taxes remain unchanged
\n(D) wages and prices are very flexible
\n(E) the Federal Reserve simultaneously
increases the reserve requirement""":"A",\

"""19. Which of the following would increase the value
of the simple spending multiplier?
\n(A) An increase in government expenditure
\n(B) An increase in exports
\n(C) A decrease in government unemployment
benefits
\n(D) A decrease in the marginal propensity
to consume
\n(E) A decrease in the marginal propensity
to save""":"E",\

"""20. Assume that the reserve requirement is
25 percent. If banks have excess reserves
of $10,000, which of the following is the
maximum amount of additional money that
can be created by the banking system through
the lending process?
\n(A) $ 2,500
\n(B) $ 10,000
\n(C) $ 40,000
\n(D) $ 50,000
\n(E) $250,000""":"C",\

"""21. A reason for requiring commercial banks to
maintain reserve balances with the Federal
Reserve is that these balances
\n(A) provide the maximum amount of reserves a
bank would ever need
\n(B) give the Federal Reserve more control over
the money-creating operations of banks
\n(C) ensure that banks do not make excessive
profits
\n(D) assist the Treasury in refinancing government
debt
\n(E) enable the government to borrow cheaply
from the Federal Reserve’s discount window""":"B",\

"""22. The purchase of government bonds from the
public in the open market by the Federal
Reserve will
\n(A) increase the supply of money
\n(B) increase the interest rate
\n(C) increase the discount rate
\n(D) decrease the number of Federal Reserve
notes in circulation
\n(E) decrease the reserve requirement""":"A",\

"""23. To counteract a recession, the Federal Reserve
could
\n(A) buy government securities on the open
market and raise the reserve requirement
\n(B) buy government securities on the open
market and lower the reserve requirement
\n(C) buy government securities on the open
market and raise the discount rate
\n(D) sell government securities on the open
market and raise the discount rate
\n(E) raise the reserve requirement and lower the
discount rate""":"B",\

"""24. Total spending in the economy is most likely to
increase by the largest amount if which of the
following occur to government spending
and taxes?
\n(A) Decrease Increase
\n(B) Decrease No change
\n(C) Increase Increase
\n(D) Increase Decrease
\n(E) No change Increase""":"D",\

"""25. According to the Keynesian model, an increase
in the money supply affects output more if
\n(A) investment is sensitive to changes in interest
rates
\n(B) money demand is sensitive to changes in
interest rates
\n(C) the unemployment rate is low
\n(D) consumption is sensitive to the Phillips
curve
\n(E) government spending is sensitive to public
opinion""":"A",\

"""26. Supply-side economists argue that
\n(A) a cut in high tax rates results in an increased
deficit and thus increases aggregate supply
\n(B) lower tax rates provide positive work
incentives and thus shift the aggregate
supply curve to the right
\n(C) the aggregate supply of goods can only be
increased if the price level falls
\n(D) increased government spending should be
used to stimulate the economy
\n(E) the government should regulate the supply
of imports""":"B",\

"""27. Which of the following policies would most
likely be recommended in an economy with
an annual inflation rate of 3 percent and an
unemployment rate of 11 percent?
\n(A) An increase in transfer payments and an
increase in the reserve requirement
\n(B) An increase in defense spending and an
increase in the discount rate
\n(C) An increase in income tax rates and a
decrease in the reserve requirement
\n(D) A decrease in government spending and the
open market sale of government securities
\n(E) A decrease in the tax rate on corporate
profits and a decrease in the discount rate""":"E",\

"""28. According to the monetarists, inflation is most
often the result of
\n(A) high federal tax rates
\n(B) increased production of capital goods
\n(C) decreased production of capital goods
\n(D) an excessive growth of the money supply
\n(E) upward shifts in the consumption function""":"D",\

"""29. An expansionary fiscal policy would most likely
cause which of the following changes in output
and interest rates?
Output Interest Rates
\n(A) Increase Increase
\n(B) Increase Decrease
\n(C) Decrease Increase
\n(D) Decrease Decrease
\n(E) No change Decrease""":"A",\

"""30. Which of the following would result in the
largest increase in aggregate demand?
\n(A) A $30 billion increase in military
expenditure and a $30 billion open
market purchase of government securities
\n(B) A $30 billion increase in military
expenditure and a $30 billion open
market sale of government securities
\n(C) A $30 billion tax decrease and a $30 billion
open market sale of government securities
\n(D) A $30 billion tax increase and a $30 billion
open market purchase of government
securities
\n(E) A $30 billion increase in social security
payments and a $30 billion open market sale
of government securities""":"A",\

"""31. Which of the following measures might be used
to reduce a federal budget deficit?\n
I. Increasing taxes\n
II. Decreasing federal spending\n
III. Decreasing interest rates
\n(A) I only
\n(B) II only
\n(C) III only
\n(D) I and III only
\n(E) I, II, and III""":"E",\

"""32. Which of the following would most likely be the
immediate result if the United States increased
tariffs on most foreign goods?
\n(A) The United States standard of living would
be higher.
\n(B) More foreign goods would be purchased
by Americans.
\n(C) Prices of domestic goods would increase.
\n(D) Large numbers of United States workers
would be laid off.
\n(E) The value of the United States dollar would
decrease against foreign currencies.""":"C",\

"""33. Which of the following policies is most likely
to encourage long-term economic growth in
a country?
\n(A) An embargo on high-technology imports
\n(B) A decrease in the number of immigrants to
the country
\n(C) An increase in government transfer
payments
\n(D) An increase in the per capita savings rate
\n(E) An increase in defense spending""":"D",\

"""34. Which of the following would occur if the
international value of the United States dollar
decreased?
\n(A) United States exports would increase.
\n(B) More gold would flow into the
United States.
\n(C) United States demand for foreign currencies
would increase.
\n(D) The United States trade deficit would
increase.
\n(E) United States citizens would pay less for
foreign goods.""":"A",\

"""35. If exchange rates are allowed to fluctuate freely
and the United States demand for Indian rupees
increases, which of the following will most
likely occur?
\n(A) The dollar price of Indian goods will
increase.
\n(B) The rupee price of United States goods
will increase.
\n(C) The United States balance-of-payments
deficits will increase.
\n(D) The dollar price of rupees will fall.
\n(E) The dollar price of Indian goods will fall.""":"A",\

"""36. A revenue-neutral replacement of some portion
of the federal personal income tax with a general
sales tax would most likely result in
\n(A) greater overall progressivity in the tax
structure
\n(B) smaller overall progressivity in the tax
structure
\n(C) stronger automatic stabilization through
the business cycle
\n(D) a larger budget deficit
\n(E) a smaller federal budget deficit""":"B",\

"""37. A deficit in the United States trade balance can
be described as
\n(A) an excess of the value of imports over the
value of exports
\n(B) an excess of the value of exports over the
value of imports
\n(C) an excess of payments to foreigners over
receipts from foreigners
\n(D) an almost complete depletion of the
gold stock
\n(E) an excess of receipts from foreigners over
payments to foreigners""":"A",\

"""38. Problems faced by all economic systems include
which of the following?\n
I. How to allocate scarce resources among
unlimited wants\n
II. How to decentralize markets
III. How to decide what to produce, how to
produce, and for whom to produce
IV. How to set government production quotas
\n(A) I only
\n(B) I and III only
\n(C) II and III only
\n(D) I, II, and III only
\n(E) I, II, III, and IV""":"B",\

"""39. An increase in which of the following will cause
an increase in the demand for a certain good?
\n(A) The price of the good
\n(B) The number of sellers of the good
\n(C) The price of a complementary good
\n(D) The cost of purchasing the good
\n(E) The number of buyers of the good""":"E",\

"""40. If the exchange rate changes from 1 United
States dollar = 100 yen to 1 United States
dollar = 80 yen, which of the following will
happen?
\n(A) United States goods will become more
expensive to Japanese consumers.
\n(B) Japanese goods will become less expensive
to United States consumers.
\n(C) United States exports to Japan will increase.
\n(D) Japanese exports to the United States will
increase.
\n(E) Japanese imports from the United States will
decrease.""":"C",\

"""41. An increase in which of the following is most
likely to cause demand-pull inflation?
\n(A) Rental price of capital
\n(B) Fuel costs
\n(C) Consumer spending
\n(D) Income taxes
\n(E) Imports of capital goods""":"C",\

"""42. Assume that last year the consumer price index
\n(CPI) was 150 and a household’s nominal
income was $30,000. If the CPI this year is 160,
to be as well off as last year, the household
should have an increase in nominal income of
\n(A) $1,800
\n(B) $1,875
\n(C) $2,000
\n(D) $3,000
\n(E) $4,800""":"C",\

"""43. The natural rate of unemployment can be
defined as the unemployment rate that exists
when the economy
\n(A) is neither growing nor shrinking
\n(B) has zero inflation
\n(C) has only cyclical and structural
unemployment
\n(D) has no trade deficit or government deficit
\n(E) produces at the full-employment output level""":"E",\

"""44. A fully anticipated expansionary fiscal policy
will cause the price level and real output to
change in which of the following ways in the
long run?
\n(A) Increase Increase
\n(B) Increase Not change
\n(C) Not change Not change
\n(D) Decrease Increase
\n(E) Decrease Decrease""":"B",\

"""45. If the nominal gross domestic product is
$8 trillion and the money supply is $2 trillion,
the velocity of money is
\n(A) 2
\n(B) 4
\n(C) 6
\n(D) 10
\n(E) 16""":"B",\

"""46. Which of the following is NOT true of the
Federal Reserve?
\n(A) It serves as a lender of last resort for
member banks.
\n(B) It supervises member banks.
\n(C) It provides check-clearing services.
\n(D) It issues debit cards.
\n(E) It controls the money supply.""":"D",\

"""47. Which of the following best describes crowding
out?
\n(A) Competition between the government and
private borrowers for loanable funds results
in an increase in interest rates.
\n(B) Increases in the costs of inputs lead to
decreases in domestic production.
\n(C) The Federal Reserve’s open-market
operations decrease the amount of funds
banks have available for lending.
\n(D) Reductions in the government’s budget
deficit lead to fewer Treasury bonds
being issued.
\n(E) The scarcity of funds forces Congress
to decrease spending on critical public
works programs.""":"A",\

"""48. Suppose that the economy is operating at
full employment. If the government wants to
discourage consumption spending, stimulate
investment spending, and maintain fullemployment
output, which of the following
combinations of monetary and fiscal policies
would most likely achieve these goals?

\n(A) Increase money
supply
Increase government
spending
\n(B) Increase money
supply
Increase personal
income taxes
\n(C) Decrease money
supply
Increase government
spending
\n(D) Decrease money
supply
Increase personal
income taxes
\n(E) Decrease money
supply
Decrease personal
income taxes""":"B",\

"""49. If the Federal Reserve suddenly increases the
growth rate of the money supply from 4 percent
to 8 percent per year, interest rates, aggregate
demand, and nominal gross domestic product
\n(GDP) will most likely change in which of the
following ways in the short run?

\n(A) Increase Increase Increase
\n(B) Increase Decrease Increase
\n(C) Decrease Increase Increase
\n(D) Decrease Increase Decrease
\n(E) Decrease Decrease Increase""":"C",\

"""50. The United States federal government budget
deficits tend to be large when which of the
following is low?
\n(A) The interest rate on government bonds
\n(B) The growth rate of the economy
\n(C) The unemployment rate
\n(D) The inflation rate
\n(E) The international value of the United
States dollar""":"B",\

"""51. Using the same amount of resources, Betaland
can produce 80 tons of corn or 80 tons of wheat
and Alphaland can produce 40 tons of corn or
20 tons of wheat. Which of the following
statements is true?
\n(A) The opportunity cost of producing a ton of
corn in Betaland is two tons of wheat.
\n(B) The opportunity cost of producing a ton of
corn in Betaland is a ton of wheat.
\n(C) The opportunity cost of producing a ton of
corn in Alphaland is two tons of wheat.
\n(D) Betaland has both the absolute and
comparative advantage in producing corn.
\n(E) Alphaland has the comparative advantage in
producing wheat.""":"B",\

"""52. If the required reserve ratio is 0.20 and the
Federal Reserve buys $200 worth of securities,
the maximum increase in the money supply
will be
\n(A) $ 200
\n(B) $ 400
\n(C) $ 600
\n(D) $ 800
\n(E) $1,000""":"E",\

"""53. The table above shows the T-account entries of
a bank. If the required reserve ratio is 0.20,
what is the maximum amount of additional
loans that this bank can make?
\n(A) $ 0
\n(B) $ 2,000
\n(C) $ 2,500
\n(D) $ 4,000
\n(E) $10,000""":"B",\

"""54. Hyperinflation is usually associated with which
of the following?
\n(A) An increase in labor productivity
\n(B) An increase in exports
\n(C) A decrease in total spending
\n(D) Appreciation of the domestic currency
\n(E) Rapid growth of the money supply""":"E",\


"""55. According to the short-run Phillips curve, which
of the following will occur when the Federal
Reserve increases the money supply?
\n(A) Both the unemployment rate and the
inflation rate will increase.
\n(B) Both the unemployment rate and the
inflation rate will decrease.
\n(C) The unemployment rate will increase,
and the inflation rate will decrease.
\n(D) The unemployment rate will decrease,
and the inflation rate will increase.
\n(E) The inflation rate will increase, but the
unemployment rate will remain constant.""":"D",\

"""56. Which of the following is true if there is a
current account deficit in the United States
balance-of-payments accounts?
\n(A) There is a corresponding deficit in the
financial account.
\n(B) There is a corresponding surplus in the
financial account.
\n(C) There is an offsetting surplus in the
government’s budget.
\n(D) There is an offsetting increase in net
exports.
\n(E) The United States dollar appreciates in the
foreign exchange market.""":"B",\

"""57. An increase in national saving will cause the real
interest rate and investment spending to change
in which of the following ways?
Real Interest Rate Investment
\n(A) Increase Increase
\n(B) Increase Decrease
\n(C) Increase Not change
\n(D) Decrease Increase
\n(E) Decrease Not change""":"D",\

"""58. To raise its long-run rate of economic growth, a
country should design and implement policies
that do which of the following?
\n(A) Encourage current consumption over saving
\n(B) Encourage saving and investment
\n(C) Increase the price level and profits
\n(D) Promote equity through income
redistribution
\n(E) Limit business activities to protect the
environment""":"B",\

"""59. With a constant money supply, an increase in
the demand for money will affect interest rates
and bond prices in which of the following ways?

\n(A) Increase Increase
\n(B) Increase Decrease
\n(C) Increase Not change
\n(D) Decrease Increase
\n(E) Not change Increase""":"B",\

"""60. According to the quantity theory of money, an
increase in the money supply results in an
increase in which of the following?
\n(A) Interest rate
\n(B) Unemployment
\n(C) Nominal gross domestic product
\n(D) The government’s budget deficit
\n(E) The value of the dollar on the foreign
exchange market""":"C",\

"""61. Which of the following policies will most
likely lead to a reduction in the natural rate
of unemployment?
\n(A) Increasing government purchases of goods
and services
\n(B) Providing more job-training programs to
help the less skilled
\n(C) Increasing the duration of unemployment
compensation
\n(D) Raising the minimum wage
\n(E) Increasing the money supply""":"B",\

"""62. Assume that an economy produces only two
goods, computers and gasoline. The quantity
and price of each are given in the table below.\n
Year |Price of Computers | Quantity |Price of Gasoline |Quantity \n
2000 |$1,000 |\t5 |$1 500 \n
2004 |$500 |10 |$2 250 \n
If the base year is 2000, how do nominal and
real gross domestic product \n(GDP) change
between 2000 and 2004?
Nominal GDP Real GDP
\n(A) No change Increase
\n(B) No change Decrease
\n(C) Increase No change
\n(D) Increase Increase
\n(E) Increase Decrease""":"A",\

"""63. Assuming that the expected inflation rate is
stable, an increase in interest rates will lead to
\n(A) an increase in bond prices
\n(B) an increase in the demand for money
as an asset
\n(C) an increase in aggregate demand
\n(D) a decrease in private investment
\n(E) a decrease in capital inflows""":"D",\

"""64. A bank has demand deposits of $100,000 and
actual reserves of $27,000. If the reserve
requirement is 10 percent, the bank can loan
out a maximum of
\n(A) $ 7,000
\n(B) $ 17,000
\n(C) $ 27,000
\n(D) $100,000
\n(E) $170,000""":"B",\

"""65. Which of the following is true of the long-run
Phillips curve?
\n(A) It shows the trade-off between the price
level and the money supply.
\n(B) It shows that lower unemployment can
be gained only at the expense of higher
inflation.
\n(C) It shows that unemployment is a monetary
issue.
\n(D) It is vertical at the natural rate of
unemployment.
\n(E) It is U-shaped over all possible ranges
of unemployment.""":"D",\

"""66. Economics is best defined as the study of how
\n(A) markets allocate resources efficiently
\n(B) businesses make investments to maximize
profits
\n(C) public goods and services are produced
\n(D) society chooses to allocate its scarce
resources
\n(E) the invisible hand of the market works""":"D",\

"""67. Human capital refers to which of the following?
\n(A) The acquisition of plant and equipment by
workers
\n(B) The amount of financial investment made by
individuals
\n(C) The labor force requirement for sustained
economic growth
\n(D) The education and experience of the labor
force
\n(E) The technology available to individual
workers""":"D",\

"""68. Which of the following will lower inflationary
expectations?
\n(A) The government’s announcement that it will
increase spending on infrastructure
\n(B) The Federal Reserve’s announcement that it
will steadily raise the federal funds rate
\n(C) An increase in the value of stocks
\n(D) An increase in consumer and business
optimism
\n(E) An increase in the money supply""":"B",\



"""69. An increase in national saving will affect the
supply of loanable funds and the real interest
rate in which of the following ways?

\n(A) Increase Increase
\n(B) Increase Decrease
\n(C) Increase No change
\n(D) Decrease Increase
\n(E) Decrease Decrease""":"B",\

"""70. Which of the following will cause the short-run
aggregate supply curve to shift to the left?
\n(A) An increase in the price level
\n(B) A decrease in the price level
\n(C) An increase in trade deficits
\n(D) An increase in nominal wages
\n(E) An increase in productivity""":"D",\

"""71. Which of the following policies will most likely
stimulate economic growth?
\n(A) A tax credit on investment spending
\n(B) Elimination of copyright and patent
protection laws
\n(C) A reduction in funding for education
\n(D) Change of the Social Security retirement
age from sixty-five to fifty-eight
\n(E) Increased government regulations for
research and development""":"A",\

"""72. The real interest rate for a consumer loan is
5 percent, and the expected inflation rate is
2 percent. What is the nominal interest rate
on the consumer loan?
\n(A) 2.5 percent
\n(B) 3 percent
\n(C) 5 percent
\n(D) 7 percent
\n(E) 10 percent""":"D",\

"""73. Which of the following groups is most likely to
benefit from unanticipated inflation?
\n(A) Creditors
\n(B) Fixed income earners
\n(C) Consumers
\n(D) Debtors
\n(E) Savers""":"D",\

"""74. Assume that there are only two countries—Eland
and Zland—that produce only two goods—X
andY. The table below shows units of each good
that each country can produce using one hour of
labor.\n
\t Good X |GoodY \n
Eland 5 or 3\n
Zland 8 or 4\n
Which of the following statements is correct?
\n(A) Eland has a comparative advantage in
producing both goods.
\n(B) Zland has an absolute advantage in
producing both goods.
\n(C) Eland’s opportunity cost for goodY is
5 units of good X.
\n(D) Zland’s opportunity cost for good X is
2 units of goodY.
\n(E) Zland should not trade with Eland because
Eland produces both goods at lower costs.""":"B",\

"""75. If both the demand for and the supply of coffee
increase, what will happen to the equilibrium
price and quantity in the coffee market?
\n(A) Increase Increase
\n(B) Increase Indeterminate
\n(C) Decrease Decrease
\n(D) Decrease Increase
\n(E) Indeterminate Increase""":"E",\

"""76. Which of the following would cause a country’s
production possibilities curve to shift outward?
\n(A) A decrease in the unemployment rate
\n(B) A technological advance
\n(C) An increase in government transfer
payments
\n(D) A reallocation of economic resources
\n(E) A decline in population\n""":"B",\

"""77. Which of the following is true about economic
growth?
\n(A) It occurs in big countries more often than it
does in small countries.
\n(B) It occurs more often in countries with closed
economies than in those with open
economies.
\n(C) It is positively related to a country’s
investment in human capital.
\n(D) It is negatively related to a country’s capital
stock.
\n(E) It is negatively related to a country’s
standard of living.\n""":"C",\

"""78. The M1 measure of the money supply primarily
consists of which of the following?
\n(A) Checking accounts and credit cards
\n(B) Noncheckable savings and credit cards
\n(C) Currency in circulation and checkable bank
deposits
\n(D) Noncheckable savings and
small-denomination time deposits
\n(E) Savings bonds and savings accounts\n""":"C",\

"""79. If a country’s consumer price index was 200 last
year and is 190 this year, which of the following
must be true for the country from last year to this
year?
\n(A) The quantity of goods produced has
decreased.
\n(B) The average quality of the goods produced
has increased.
\n(C) The inflation rate has increased by 5 percent.
\n(D) The price level has decreased by 5 percent.
\n(E) The unemployment rate has decreased by
5 percent.\n""":"D",\

"""80. The national debt of the United States is the
\n(A) accumulated government spending, less the
interest paid on bonds
\n(B) accumulation of all past government deficits
\n(C) difference between government tax revenues
and government spending during a fiscal
year
\n(D) money owed to the Federal Reserve for
reimbursement of domestic bondholders
\n(E) annual amount borrowed by local, state, and
federal governments to provide public goods
to all citizens""":"B",\

"""81. Gross domestic product is defined as which of
the following?
\n(A) The total amount of output produced by
an economy in a given time period
\n(B) The total market value of all output
produced by an economy in a given time
period
\n(C) The total market value of all final goods and
services produced by an economy in a given
time period
\n(D) The total value of all final goods and
services sold in the domestic market in a
given time period
\n(E) The total market value of all final goods and
services produced by an economy minus the
market value of final goods and services
exported to other nations in a given time
period""":"C",\


"""82. If central banks in Asia reduce the supply of
their own currencies on the foreign-exchange
market relative to the United States dollar, which
of the following will occur?
\n(A) Asian currencies will depreciate.
\n(B) The United States dollar will appreciate.
\n(C) Asian goods will be more expensive for
United States consumers.
\n(D) United States goods will be more expensive
for Asian consumers.
\n(E) United States private investment in Asia will
increase.""":"C",\

"""83. Which of the following policy actions could the
Federal Reserve use to combat inflation?
\n(A) Selling government bonds to reduce the
money supply
\n(B) Buying government bonds to reduce the
amount of loanable funds
\n(C) Raising taxes to reduce the interest rate
\n(D) Cutting the reserve requirement to reduce
the amount of excess reserves held by banks
\n(E) Cutting the discount rate to decrease the
availability of loans to banks""":"A",\

"""84. Jamal lost his computer programming job when
it was outsourced to a company abroad. After
looking unsuccessfully for several months for
another job, he gave up and returned to school to
receive training to become a physical therapist.
Currently Jamal is classified as
\n(A) structurally unemployed
\n(B) frictionally unemployed
\n(C) cyclically unemployed
\n(D) underemployed
\n(E) not in the labor force""":"E",\

"""85. Which of the following will decrease gross
domestic product by the greatest amount?
\n(A) $20 billion increases in both government
spending and taxes
\n(B) $20 billion decreases in both government
spending and taxes
\n(C) A $20 billion increase in taxes
\n(D) A $20 billion decrease in government
spending
\n(E) A $20 billion increase in net exports""":"D"}\
